name: Build Design System

on:
  push:
    branches: [main]
    paths:
      - 'tokens/**'
      - 'scripts/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Download fonts
        run: node scripts/download-fonts.js
        
      - name: Build design system
        run: node scripts/generate-all.js
        
      - name: Commit generated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/ fonts/
          git diff --staged --quiet || git commit -m "chore: regenerate design system [skip ci]"
          git push
